== Pattern Matching en Java (10 ?)
(by Remi Forax)

=== Projet Valhalla

2 features : http://openjdk.java.net/projects/valhalla/

* Value types
* Generic sur primitive et value types

=== Projet Valhalla

Ce qui ne va pas avec les objets

* Chaque objet a un header de 64 bits
* Les tableaux d'objets sont des tableaux de reference
* On crée trop de références
* Le rapport du coût d'accès la mémoire / CPU est très cher aujourd'hui

=== Projet Valhalla

Intérêt des Value Type

* idem struct C
* pas d'identité (pas d'adresse mémoire)
* List<complex> implémenté comme un tableau de complex (adjacents) et pas un tableau de pointeurs de complex

=== Projet Panama

* Appel de C a partir de java
* Accéder aux opérateurs SIMD (exemple : int sur 512 bits)

=== Projet Amber

* Extension des lambda
** Gestion des underscores (paramètres non nommés)
* Extension de l'inférence de type
** Classes anonymes
* Enums avec Generics

=== Java 10

* Roadmap : Intègrer les fonctionnalités des projets Panama et Valhalla

=== JEP 305 : Pattern Matching

Switch sur les types demandé depuis 97

* switch case sur les types des objets
* switch retourne une valeur

Implique d'intégrer dans java les hiérachies fermées (typage algébrique)

=== JEP 305 : Exemple de code

[source]
----
int eval(Node n) {
    switch(n) {
        case IntNode(int i): return i;
        case NegNode(Node n): return -eval(n);
        case AddNode(Node left, Node right): return eval(left) + eval(right);
        case MulNode(Node left, Node right): return eval(left) * eval(right);
        default: throw new IllegalStateException(n);
    };
}
----